redis:
  host: localhost
  port: 4430
  useTls: true
  clientName: "lettuce-test-app"
  database: 0
  #timeout: 1000s
  #password: "password"
  verifyPeer: false

test:
  mode: standalone  # or cluster
  clients: 1  # Number of client instances
  connectionsPerClient: 1  # Number of connections per client
  workload:
    type: get_set_async     # Options: get_set, multi, pub_sub
    maxDuration: PT60S  # Max duration in seconds per workload
clientOptions:
  autoReconnect: true
  pingBeforeActivate: true
  disconnectedBehavior: REJECT_COMMANDS  #Options: DEFAULT, ACCEPT_COMMANDS, REJECT_COMMANDS
  socketOptions:
    tcpUserTimeoutOptions:
      tcpUserTimeout: PT7875S # 7875s
      enabled: true
    keepAliveOptions:
      interval: PT75S #75s
      idle: PT2H # 2h
      count: 9
metrics:
  logging:
    enable: true
    step: 1s # Step size (i.e. reporting frequency)
  influx:
    enable: false
    uri: http://localhost:8086
    db: 1
    autoCreateDb: true
    step: 1s # Step size (i.e. reporting frequency)
