redis:
  clientName: "lettuce-test-app"
  host: localhost
  port: 6379
  useTls: false
  #username: "default"
  #password: "password"
  verifyPeer: false
  database: 0
  #timeout: 1000s



test:
  mode: standalone  # or cluster
  clients: 1 # Number of client instances
  connectionsPerClient: 1  # Number of connections per client
  workload:
    type: get_set_async # Available workload types:
                        # Standalone mode: redis_commands, get_set, multi, pub_sub, get_set_async
                        # Cluster mode: get_set
    maxDuration: PT60S  # Max duration in seconds per workload
    options: # Options specific per workload. See below for example configuration of get_set_async workload
      getSetRatio: 0.5      # 50% of operations are get, 50% are set
      valueSize: 1       # 1 characters
      operationCount: 1000   # 1000 operations per workload

clientOptions:
  autoReconnect: true
  reconnectOptions:
    fixedDelay: PT0.001S # 1ms Configures constant delay between re-connection attempts
  pingBeforeActivate: false
  #disconnectedBehavior: REJECT_COMMANDS  #Options: DEFAULT, ACCEPT_COMMANDS, REJECT_COMMANDS
  timeoutOptions: # Options to configure command timeouts
      fixedTimeout: PT1S # 1 s
  socketOptions:  # Options to configure low-level socket options for the connections kept to Redis servers.
    connectTimeout: PT10S # 10 s
    tcpUserTimeoutOptions:
      tcpUserTimeout: PT7875S # 7875s
      enabled: true
    keepAliveOptions:
      interval: PT75S #75s
      idle: PT2H # 2h
      count: 9

metrics:
  logging:
    enable: true
    step: 5s # Step size (i.e. reporting frequency)
  influx:
    enable: false
    uri: http://localhost:8086
    db: 1
    autoCreateDb: true
    step: 5s # Step size (i.e. reporting frequency)
