runner:
  redis:
    clientName: "lettuce-test-app"
    host: localhost
    port: 6379
    useTls: false
    #username: "default"
    #password: "password"
    verifyPeer: false
    #database: 0
    #timeout: 1000s

  test:
    mode: standalone  # standalone or cluster
    clients: 1 # Number of client instances
    connectionsPerClient: 1  # Number of connections per client
    threadsPerConnection: 1  # Number of threads sharing same connection
    workload:
      type: get_set_async # Available workload types:
                          # Standalone mode: redis_commands, get_set, multi, pub_sub, get_set_async
                          # Cluster mode: get_set, get_set_async, pub_sub, redis_commands, redis_commands_async
      maxDuration: PT1M   # Max duration in seconds per workload
      options: # Options specific per workload. See below for example configuration of get_set_async workload
        getSetRatio: 0.9      # 50% of operations are get, 50% are set
        valueSize: 100        # 100 characters
        iterationCount: 1000  # How many iterations to run of the workload before finishing
        #delayAfterIteration: PT0S # 0s  Delay after each iteration
        #delayAfterWorkload: PT1S   # 0s  Delay after each workload
        #elementsCount: 1     # 1 elements per operation E.g how many elements to push with a `lpush`
        #transactionSize: 100    # 100 E.g. how many commands to run in a `multi`
        #awaitAllResponses: true  # true E.g. whether to await all responses before sending next command batch in GetSetAsyncWorkload
        #keyGenerationStrategy: RANDOM  # RANDOM Options: RANDOM, SEQUENTIAL;
        #keyPattern: "key-%d"   # key-%d Key pattern to use for key generation
        keyRangeMin: 0         # 0 Minimum key range
        keyRangeMax: 1000     # 10000 Maximum key range
  clientOptions:
    metricsOptions:
      commandLatencyMonitoring: true # Enables Lettuce internal command latency monitoring
      connectionMonitoring: true     # Enables Additional metrics for connection inacive time. Note supported with GA build of lettuce, and required custom Lettuce client build.  See README.md for instruction ho to enable them
    autoReconnect: true
    #reconnectOptions:
    #  fixedDelay: PT1S # 1s Configures constant delay between re-connection attempts
    #pingBeforeActivate: false
    #requestQueueSize: 2147483647 # 2^31-1 Set the per-connection request queue size.
                                  # The command invocation will lead to a {@link RedisException} if the queue size is exceeded. Default is {@link Integer#MAX_VALUE}.
    #disconnectedBehavior: REJECT_COMMANDS  #Options: DEFAULT, ACCEPT_COMMANDS, REJECT_COMMANDS
    #timeoutOptions: # Options to configure command timeouts
    #    fixedTimeout: PT1S # 1 s
    #socketOptions:  # Options to configure low-level socket options for the connections kept to Redis servers.
    #  connectTimeout: PT10S # 10 s
    #  tcpUserTimeoutOptions:
    #    tcpUserTimeout: PT7875S # 7875s
    #    enabled: true
    #  keepAliveOptions:
    #    interval: PT75S #75s
    #    idle: PT2H # 2h
    #    count: 9
  clusterClientOptions:
    topologyRefreshOptions:
      adaptive:
        enabled: true
        refreshTriggers: ALL
        triggersTimeout: PT30S
    validateClusterNodeMembership: true