name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Check code formatting
        run: mvn formatter:validate

      - name: Build and verify lettuce-test-app
        run: |
          echo "Building lettuce-test-app with lettuce-core snapshot version"
          mvn -B clean verify

      - name: Run integration tests
        run: |
          echo "Running integration tests"
          mvn test